# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('currency', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=32)),
                ('transaction_id', models.CharField(max_length=50)),
                ('billing_amount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('billing_currency', models.CharField(max_length=5)),
                ('transaction_amount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('transaction_currency', models.CharField(max_length=5)),
                ('settlement_amount', models.DecimalField(decimal_places=5, max_digits=50, null=True)),
                ('settlement_currency', models.CharField(max_length=5, null=True)),
                ('transferred_on', models.DateTimeField(auto_now_add=True)),
                ('transfer_status', models.CharField(choices=[(b'AU', b'authorisation'), (b'PR', b'presentment')], default='PR', max_length=2)),
                ('merchant_name', models.CharField(max_length=100, null=True)),
                ('merchant_country', models.CharField(max_length=3, null=True)),
                ('merchant_mcc', models.CharField(max_length=20, null=True)),
                ('merchant_city', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=32)),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('currency', models.CharField(max_length=5)),
                ('transferred_on', models.DateTimeField(auto_now_add=True)),
                ('transfer_type', models.CharField(choices=[(b'DE', b'Debit'), (b'CR', b'Credit')], default='CR', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
